### PR TITLE
Changed "Validate" to "Confirm" to avoid the English language police

### PR DESCRIPTION
**Pull request by Julien-cpsn**

### CODE REVIEW

**Comment by ccoVeille** [comment]
You made me laugh so much with "to avoid English police" 🤣😅😂

**Comment by Julien-cpsn** [comment]
@ccoVeille haha I said this because I personally know @AirOne01 we are both from Lyon

**Comment by ccoVeille** [comment]
> @ccoVeille haha I said this because I personally know @AirOne01 we are both from Lyon

Villeurbanne, here ! Grand Lyon represents !

**Comment by Julien-cpsn** [comment]
Yes Villeurbanne too :)

**Comment by AirOne01** [comment]
> PS : the issue number is 69

LMAO I didn't see that 😂 that's awesome

**Comment by ccoVeille** [comment]
People who are not from France, won't get the joke, and I will think about dirty things, haha

https://en.wikipedia.org/wiki/Rh%C3%B4ne_(department)

Department number	69

**Comment by G0V1NDS** [comment]
This change caused issue with vim bindings, getting below error when running atac:
```
Error:
	Could not parse key bindings file
	TOML parse error at line 19, column 1
   |
19 | [keybindings.generic.text_inputs.text_input]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
missing field `validate`
```

**Comment by Julien-cpsn** [comment]
> This change caused issue with vim bindings, getting below error when running atac:
> ```
> Error:
> 	Could not parse key bindings file
> 	TOML parse error at line 19, column 1
>    |
> 19 | [keybindings.generic.text_inputs.text_input]
>    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> missing field `validate`
> ```

Hello,

Which version are you using?

**Comment by G0V1NDS** [comment]
Had installed latest version from homebrew:
```
atac 0.15.1
```
Using vim bindings file mentioned in repo:
https://github.com/Julien-cpsn/ATAC/blob/main/key_bindings_templates/vim_key_bindings.toml

```
# Collection name, request name, URL, Header, Query param, Basic Auth, Bearer Token
[keybindings.generic.text_inputs.text_input]
cancel = "Esc"
# confirm = "Enter" # -> This is causing issue
validate = "Enter" # -> This fixes issue
```

**Comment by Julien-cpsn** [comment]
Hello @G0V1NDS 

I understand the issue, the commit that changes "validate" into "confirm" is not released yet but is on the main branch. Since you installed the app with homebrew, you don't have the other files linked to the app, so you got to the main branch, unfortunately it's not the great version of the file!

It's temporary until the new release then!
I didn't not think of that

Have a great day

**Comment by G0V1NDS** [comment]
Understood, Anyways I stopped using vim bindings so problem is sorted for now.

**Pull request merged**
