### PR TITLE
feat: home/end binding for request body edit

### PR DESCRIPTION
**Pull request by Frank-III**
resolve: #93,

Should I do it for other textarea?

### CODE REVIEW

**Comment by Julien-cpsn** [comment]
Hi!

You forgot to update the example key bindings files. Otherwise, everything is fine. 

Simple and efficient 👍

Have a great day

**Comment by Frank-III** [comment]
> Hi!
> 
> You forgot to update the example key bindings files. Otherwise, everything is fine.
> 
> Simple and efficient 👍

Done! Thank you for the prompt reply.

>Adding this feature for the other text input will not be hard since it's a one-line string
>
>Have a great day

Should I do it in this PR or a new one?

**Comment by Julien-cpsn** [comment]
> 
> Should I do it in this PR or a new one?
> 

This PR would be great!

**Comment by Frank-III** [comment]
Done!

**Comment by Frank-III** [comment]
Hi! Another blocker here?

**Comment by Julien-cpsn** [comment]
> Hi! Another blocker here?

Hello!

No everything is fine. I am starting a PhD and I don't have much time right now. You're priority number one when going back to atac 

Have a great day

**Pull request merged**
