### PR TITLE
feat(copy): add cli-clipboard and allow to copy result tabs

### PR DESCRIPTION
**Pull request by NachoNievaG**
Hi!
First of all, thanks for starting this project.

I added the capability of copying the content of the current active result tab (which applies to result body, cookies and headers).
Also, applied the copy event to `y` (for yank).

output

### CODE REVIEW

**Comment by Julien-cpsn** [comment]
Hello man!

Great work here. You could not have know before be I was just reword all the key inputs and event system, so it doesn't fit right.
Also I already did an implemtation locally about copying the response body. But yours is great because it also allow to copy headers and cookies (which I didn't thought of).

So I will probably close the PR but a very similar code as yours will be implemented.
I will tag you when it happens

**Comment by NachoNievaG** [comment]
If you want, i can wait to adapt this to the new inputs and events system, there is no problem from my side.
Also, I was looking for a way to copy the whole "current request to launch" as a curl, to be easily exportable.

**Comment by Julien-cpsn** [comment]
> If you want, i can wait to adapt this to the new inputs and events system, there is no problem from my side.

Don't worry I'll do it haha. Also, I do have a question, was the code hard to understand/work with?

> Also, I was looking for a way to copy the whole "current request to launch" as a curl, to be easily exportable/shareable.

Yes I is planned here https://github.com/Julien-cpsn/ATAC/blob/main/README.md#L208

**Comment by NachoNievaG** [comment]
> was the code hard to understand/work with?
Not at all, I do not usually go to the source code as I try a new tool, but the lack of copy+pasting got a grind of my gears.
The whole initial product looks great, and the code base seems fairly comfortable to explore.
I've been looking for this for a while, for a sec even tried to make a TUI API client using go + charm.sh products but failed because of the lack of time to apply to it. But using Rust is also a drive for me.

**Comment by Julien-cpsn** [comment]
Closed in favor of https://github.com/Julien-cpsn/ATAC/pull/47

**Pull request closed without merging**
